# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_compute_matrices <- function(Am, Dm, seq1, seq2, gap, miss, match) {
    .Call(`_NeedlemanWunsch_rcpp_compute_matrices`, Am, Dm, seq1, seq2, gap, miss, match)
}

